go test -run TestHashAndEqual
go test -run TestStateInherit
go test -run estNextStates
go test -run TestBasic
go test -run TestBfsFind 
go test -run TestBfsFindAll1
go test -run TestBfsFindAll2
go test -run TestBfsFindAll3
go test -run TestRandomWalkFindAll
go test -run TestRandomWalkFind
